const char *textHtml404 = "<!DOCTYPE>\n"
"<html>\n"
"  <head>\n"
"    <title>404</title>\n"
"  </head>\n"
"  <body>\n"
"    <h2>Error: File not found</h2>\n"
"    <a> File not found </a>\n"
"  </body>\n"
"</html>";

const char *textHtmlError = "<!DOCTYPE>\n"
"<html>\n"
"  <head>\n"
"    <meta charset=\"UTF-8\">\n"
"    <title>!EN</title>\n"
"  </head>\n"
"  <body>\n"
"    <h1>ERROR: !EN</h1>\n"
"    <a href=\"https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/!EN\">Mozilla Web Docs - !EN</a>\n"
"  </body>\n"
"</html>\n";
